name: MFC
plugin: ./plugins/mfc
siteUrl: https://www.myfreecams.com/
urlback: ""
enable: true
recorder: scripts/record_ffmpeg.sh
scanInterval: 300
mfcWebSocket: true
modernLogin: false
mfcautolog: false
streamers:
  - 3623822
  - 12513225
